In [2]:
# Can get realitve import to work
#from .. import project_functions # This is called a relative import
#df = project_functions.load_and_process(url_or_path_to_csv_file)
#df



import pandas as pd
import numpy as np
import pandas_profiling
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

def load_and_process(data):
    df = pd.read_csv(data)
    blueTeam = (
        df.query('blueWins == 1').assign(
            KDA = lambda x: x['blueKills'] + x['blueAssists']/x['blueDeaths'],
            losingTeamKDA = lambda x: x['blueKills'] + x['blueAssists']/x['blueDeaths']
            ).rename(columns={"blueWardsPlaced":"wardsPlaced","blueWardsDestroyed":"wardsDestroyed","redWardsPlaced":"losingTeamWardsPlaced","redWardsDestroyed":"losingTeamWardsDestroyed",
                     "blueKills":"kills", "blueDeaths":"deaths","blueKDA":"KDA", "blueDragons":"dragonsTaken",
                     "blueAssits":"assits","blueEliteMonsters":"eliteMonsters", "blueHeralds":"heraldsTaken","blueTower":"towersTaken","blueTotalGold":"totalGold","blueAvgLevel":"avgLevel","blueTotalMinionsKilled":"totalMinionsKilled",
                     "blueGoldDiff":"goldDiff","blueCSPerMin":"csPerMin","redTowersDestoryed":"losingTeamTowersDestoried","blueTowersDestoried":'towerDestoried',
                      "blueAssits":"assists","blueExperienceDiff":"experienceDiff","redGoldPerMin":"losingTeamGoldPerMin","blueTowersDestroyed":"towersLost"
                    ,"blueTotalExperience":"totalExperience","blueFirstBlood":"firstBlood","redFirstBlood":"losingTeamFirstBlood","blueAssists":"assists","redAssists":"losingTeamAssits","blueGoldPerMin":"goldPerMin",
                    "blueTotalJungleMinionsKilled":"totalJungleMinionsKilled", "redTotalJungleMinionsKilled":"losingTeamTotalJungleMinionsKilled","redKills":"losingteamKills", "redDeaths":"losingTeamDeaths",
                    "redEliteMonsters":"losingTeamEliteMonsters","redDragons":"losingTeamDragons","redHeralds":"losingTeamHeralds","redTowersDestroyed":"losingTeamTowersDestroyed","redTeamGold":"losingTeamGold",
                    "redAvgLevel":"losingTeamAvgLevel","redTotalExperience":"losingTeamTotalExperience","redTotalMinionsKilled":"losingTeamTotalMinionsKilled","redTotalGold":"losingTeamTotalGold",
                    "redGoldDiff":"losingTeamGoldDiff","redCSPerMin":"losingTeamCSPerMin","redExperienceDiff":"losingTeamExperienceDiff" }).reset_index(drop=True, inplace=True)
        
    )
    redTeam =(
         df.query('blueWins == 0').assign(
            KDA = lambda x: x['redKills'] + x['redAssists']/x['redDeaths'],
            losingTeamKDA = lambda x: x['blueKills'] + x['blueAssists']/x['blueDeaths']
         ).rename(columns={"redWardsPlaced":"wardsPlaced","redWardsDestroyed":"wardsDestroyed","blueWardsPlaced":"losingTeamWardsPlaced","blueWardsDestroyed":"losingTeamWardsDestroyed","redKills":"kills", "redDeaths":"deaths", "redDragons":"dragonsTaken",
                 "redAssits":"assists","redEliteMonsters":"eliteMonsters", "redHeralds":"heraldsTaken","redTower":"towersTaken","redTotalGold":"totalGold","redAvgLevel":"avgLevel","redTotalMinionsKilled":"totalMinionsKilled",
                  "redGoldDiff":"goldDiff","redCSPerMin":"csPerMin","redGoldPerMin":"goldPerMin","blueTowersDestoried":'losingTeamTowersDestoried',"redTowersDestoryed":'towersLost',"redExperienceDiff":"experienceDiff","blueExperienceDiff":"losingTeamExperienceDiff" ,
                 "blueGoldPerMin":"losingTeamGoldPerMin","redTowersTaken":"losingTeanTowersTaken","redTotalExperience":"totalExperience",
                  "redAssists":"assists","blueAssists":"losingTeamAssits","redTowersDestroyed":"towersLost","redTotalJungleMinionsKilled":"totalJungleMinionsKilled", "blueTotalJungleMinionsKilled":"losingTeamTotalJungleMinionsKilled",
                  "blueKills":"losingteamKills", "blueDeaths":"losingTeamDeaths",
                   "blueEliteMonsters":"losingTeamEliteMonsters","blueDragons":"losingTeamDragons","blueHeralds":"losingTeamHeralds","blueTowersDestroyed":"losingTeamTowersDestroyed","blueTeamGold":"losingTeamGold"
                   ,"blueAvgLevel":"losingTeamAvgLevel","blueTotalExperience":"losingTeamTotalExperience","blueTotalMinionsKilled":"losingTeamTotalMinionsKilled",
                   "blueGoldDiff":"losingTeamGoldDiff","blueCSPerMin":"losingTeamCSPerMin","blueTotalGold":"losingTeamTotalGold","redFirstBlood":"firstBlood","blueFirstBlood":"losingTeamFirstBlood"}).reset_index(drop=True)
    )
    frames = [blueTeam,redTeam]
    df1 = pd.concat(frames).reset_index(drop=True).sort_values(by='gameId', ascending =True)
    return df1

df = load_and_process("../../data/raw/data.csv")

In [82]:
#Checking varible types
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4949 entries, 3445 to 4944
Data columns (total 42 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   gameId                              4949 non-null   int64
 1   blueWins                            4949 non-null   int64
 2   losingTeamWardsPlaced               4949 non-null   int64
 3   losingTeamWardsDestroyed            4949 non-null   int64
 4   losingTeamFirstBlood                4949 non-null   int64
 5   losingteamKills                     4949 non-null   int64
 6   losingTeamDeaths                    4949 non-null   int64
 7   losingTeamAssits                    4949 non-null   int64
 8   losingTeamEliteMonsters             4949 non-null   int64
 9   losingTeamDragons                   4949 non-null   int64
 10  losingTeamHeralds                   4949 non-null   int64
 11  losingTeamTowersDestroyed           4949 non-null   int64
 12  losingTeamTotalGold                 4949 non-null   int64
 13  losingTeamAvgLevel                  4949 non-null   float64
 14  losingTeamTotalExperience           4949 non-null   int64
 15  losingTeamTotalMinionsKilled        4949 non-null   int64
 16  losingTeamTotalJungleMinionsKilled  4949 non-null   int64
 17  losingTeamGoldDiff                  4949 non-null   int64
 18  losingTeamExperienceDiff            4949 non-null   int64
 19  losingTeamCSPerMin                  4949 non-null   float64
 20  losingTeamGoldPerMin                4949 non-null   float64
 21  wardsPlaced                         4949 non-null   int64
 22  wardsDestroyed                      4949 non-null   int64
 23  firstBlood                          4949 non-null   int64
 24  kills                               4949 non-null   int64
 25  deaths                              4949 non-null   int64
 26  assists                             4949 non-null   int64
 27  eliteMonsters                       4949 non-null   int64
 28  dragonsTaken                        4949 non-null   int64
 29  heraldsTaken                        4949 non-null   int64
 30  towersLost                          4949 non-null   int64
 31  totalGold                           4949 non-null   int64
 32  avgLevel                            4949 non-null   float64
 33  totalExperience                     4949 non-null   int64
 34  totalMinionsKilled                  4949 non-null   int64
 35  totalJungleMinionsKilled            4949 non-null   int64
 36  goldDiff                            4949 non-null   int64
 37  experienceDiff                      4949 non-null   int64
 38  csPerMin                            4949 non-null   float64
 39  goldPerMin                          4949 non-null   float64
 40  KDA                                 4949 non-null   float64
 41  losingTeamKDA                       4948 non-null   float64
dtypes: float64(8), int64(34)
memory usage: 1.6 MB

,gameId,blueWins,losingTeamWardsPlaced,losingTeamWardsDestroyed,losingTeamFirstBlood,losingteamKills,losingTeamDeaths,losingTeamAssits,losingTeamEliteMonsters,losingTeamDragons,...,avgLevel,totalExperience,totalMinionsKilled,totalJungleMinionsKilled,goldDiff,experienceDiff,csPerMin,goldPerMin,KDA,losingTeamKDA
3445,4296036692,0,15,5,1,9,7,10,1,1,...,6.8,18066,252,45,-339,-261,25.2,1676.3,8.111111,10.428571
3643,4296354535,0,16,5,1,12,3,14,1,1,...,6.6,16600,207,52,-4188,-2399,20.7,1484.3,3.166667,16.666667
4168,4297422468,0,18,2,0,4,6,0,0,0,...,7.2,18607,247,56,2713,1237,24.7,1754.0,8.750000,4.000000
2592,4378558412,0,16,3,0,8,11,9,0,0,...,7.2,18356,190,52,1867,2002,19.0,1823.8,12.375000,8.818182
2475,4379661286,0,16,1,0,5,9,3,1,1,...,6.6,17245,252,49,3014,357,25.2,1811.5,11.600000,5.333333

In [89]:
print(df.shape)

(4949, 42)

In [91]:
#looking max values to see if anything intresting
df.apply(np.max)

gameId                                4.296037e+09
blueWins                              0.000000e+00
losingTeamWardsPlaced                 5.000000e+00
losingTeamWardsDestroyed              0.000000e+00
losingTeamFirstBlood                  0.000000e+00
losingteamKills                       0.000000e+00
losingTeamDeaths                      0.000000e+00
losingTeamAssits                      0.000000e+00
losingTeamEliteMonsters               0.000000e+00
losingTeamDragons                     0.000000e+00
losingTeamHeralds                     0.000000e+00
losingTeamTowersDestroyed             0.000000e+00
losingTeamTotalGold                   1.073000e+04
losingTeamAvgLevel                    4.600000e+00
losingTeamTotalExperience             1.009800e+04
losingTeamTotalMinionsKilled          9.000000e+01
losingTeamTotalJungleMinionsKilled    0.000000e+00
losingTeamGoldDiff                   -1.083000e+04
losingTeamExperienceDiff             -9.333000e+03
losingTeamCSPerMin                    9.000000e+00
losingTeamGoldPerMin                  1.073000e+03
wardsPlaced                           7.000000e+00
wardsDestroyed                        0.000000e+00
firstBlood                            0.000000e+00
kills                                 0.000000e+00
deaths                                0.000000e+00
assists                               0.000000e+00
eliteMonsters                         0.000000e+00
dragonsTaken                          0.000000e+00
heraldsTaken                          0.000000e+00
towersLost                            0.000000e+00
totalGold                             1.289100e+04
avgLevel                              6.000000e+00
totalExperience                       1.402900e+04
totalMinionsKilled                    1.430000e+02
totalJungleMinionsKilled              1.700000e+01
goldDiff                             -6.744000e+03
experienceDiff                       -5.355000e+03
csPerMin                              1.430000e+01
goldPerMin                            1.289100e+03
KDA                                   0.000000e+00
losingTeamKDA                         0.000000e+00
dtype: float64

In [92]:
#Checking min values to see the best or worst they can do and still win
df.apply(np.min)

gameId                                4.296037e+09
blueWins                              0.000000e+00
losingTeamWardsPlaced                 5.000000e+00
losingTeamWardsDestroyed              0.000000e+00
losingTeamFirstBlood                  0.000000e+00
losingteamKills                       0.000000e+00
losingTeamDeaths                      0.000000e+00
losingTeamAssits                      0.000000e+00
losingTeamEliteMonsters               0.000000e+00
losingTeamDragons                     0.000000e+00
losingTeamHeralds                     0.000000e+00
losingTeamTowersDestroyed             0.000000e+00
losingTeamTotalGold                   1.073000e+04
losingTeamAvgLevel                    4.600000e+00
losingTeamTotalExperience             1.009800e+04
losingTeamTotalMinionsKilled          9.000000e+01
losingTeamTotalJungleMinionsKilled    0.000000e+00
losingTeamGoldDiff                   -1.083000e+04
losingTeamExperienceDiff             -9.333000e+03
losingTeamCSPerMin                    9.000000e+00
losingTeamGoldPerMin                  1.073000e+03
wardsPlaced                           7.000000e+00
wardsDestroyed                        0.000000e+00
firstBlood                            0.000000e+00
kills                                 0.000000e+00
deaths                                0.000000e+00
assists                               0.000000e+00
eliteMonsters                         0.000000e+00
dragonsTaken                          0.000000e+00
heraldsTaken                          0.000000e+00
towersLost                            0.000000e+00
totalGold                             1.289100e+04
avgLevel                              6.000000e+00
totalExperience                       1.402900e+04
totalMinionsKilled                    1.430000e+02
totalJungleMinionsKilled              1.700000e+01
goldDiff                             -6.744000e+03
experienceDiff                       -5.355000e+03
csPerMin                              1.430000e+01
goldPerMin                            1.289100e+03
KDA                                   0.000000e+00
losingTeamKDA                         0.000000e+00
dtype: float64

In [101]:
#Look to see the realtion between kills and losing team kills, compared to the other major obectives
df.groupby(['kills'])[('losingteamKills','eliteMonsters','dragonsTaken')].describe(percentiles=[])

<ipython-input-101-8e934454efc1>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['kills'])[('losingteamKills','eliteMonsters','dragonsTaken')].describe(percentiles=[])

      losingteamKills                                     eliteMonsters  \
                count      mean       std  min  50%   max         count
kills
0                10.0  3.600000  1.646545  1.0  4.0   6.0          10.0
1                42.0  4.095238  2.397250  0.0  4.0   9.0          42.0
2               146.0  4.417808  2.321583  1.0  4.0  11.0         146.0
3               303.0  4.610561  2.652030  0.0  4.0  15.0         303.0
4               430.0  4.841860  2.534262  0.0  5.0  15.0         430.0
5               612.0  4.831699  2.577018  0.0  5.0  16.0         612.0
6               635.0  5.256693  2.682799  0.0  5.0  15.0         635.0
7               668.0  5.196108  2.502565  0.0  5.0  15.0         668.0
8               609.0  5.510673  2.584169  0.0  5.0  14.0         609.0
9               499.0  5.162325  2.562414  0.0  5.0  13.0         499.0
10              341.0  5.636364  2.654025  0.0  6.0  14.0         341.0
11              267.0  5.411985  2.747987  0.0  5.0  14.0         267.0
12              177.0  5.564972  2.700487  0.0  5.0  15.0         177.0
13               94.0  5.585106  2.398071  1.0  5.0  12.0          94.0
14               59.0  5.627119  2.827807  1.0  6.0  12.0          59.0
15               30.0  5.933333  2.572177  0.0  6.0  10.0          30.0
16               19.0  6.421053  3.060788  1.0  6.0  11.0          19.0
17                3.0  6.000000  2.645751  4.0  5.0   9.0           3.0
18                2.0  9.000000  0.000000  9.0  9.0   9.0           2.0
19                2.0  3.500000  2.121320  2.0  3.5   5.0           2.0
22                1.0  5.000000       NaN  5.0  5.0   5.0           1.0

                                         dragonsTaken                      \
           mean       std  min  50%  max        count      mean       std
kills
0      0.500000  0.527046  0.0  0.5  1.0         10.0  0.500000  0.527046
1      0.523810  0.551632  0.0  0.5  2.0         42.0  0.357143  0.484966
2      0.616438  0.590269  0.0  1.0  2.0        146.0  0.472603  0.500967
3      0.570957  0.620362  0.0  1.0  2.0        303.0  0.419142  0.494235
4      0.630233  0.614902  0.0  1.0  2.0        430.0  0.462791  0.499194
5      0.709150  0.655118  0.0  1.0  2.0        612.0  0.526144  0.499724
6      0.699213  0.656861  0.0  1.0  2.0        635.0  0.496063  0.500379
7      0.718563  0.642206  0.0  1.0  2.0        668.0  0.528443  0.499564
8      0.771757  0.663020  0.0  1.0  2.0        609.0  0.536946  0.499043
9      0.723447  0.639772  0.0  1.0  2.0        499.0  0.517034  0.500211
10     0.777126  0.639535  0.0  1.0  2.0        341.0  0.557185  0.497449
11     0.797753  0.634469  0.0  1.0  2.0        267.0  0.614232  0.487690
12     0.728814  0.661365  0.0  1.0  2.0        177.0  0.519774  0.501026
13     0.691489  0.605114  0.0  1.0  2.0         94.0  0.531915  0.501656
14     0.779661  0.696489  0.0  1.0  2.0         59.0  0.525424  0.503640
15     0.933333  0.691492  0.0  1.0  2.0         30.0  0.666667  0.479463
16     1.000000  0.666667  0.0  1.0  2.0         19.0  0.684211  0.477567
17     0.666667  0.577350  0.0  1.0  1.0          3.0  0.333333  0.577350
18     1.000000  0.000000  1.0  1.0  1.0          2.0  0.500000  0.707107
19     1.500000  0.707107  1.0  1.5  2.0          2.0  1.000000  0.000000
22     0.000000       NaN  0.0  0.0  0.0          1.0  0.000000       NaN


       min  50%  max
kills
0      0.0  0.5  1.0
1      0.0  0.0  1.0
2      0.0  0.0  1.0
3      0.0  0.0  1.0
4      0.0  0.0  1.0
5      0.0  1.0  1.0
6      0.0  0.0  1.0
7      0.0  1.0  1.0
8      0.0  1.0  1.0
9      0.0  1.0  1.0
10     0.0  1.0  1.0
11     0.0  1.0  1.0
12     0.0  1.0  1.0
13     0.0  1.0  1.0
14     0.0  1.0  1.0
15     0.0  1.0  1.0
16     0.0  1.0  1.0
17     0.0  0.0  1.0
18     0.0  0.5  1.0
19     1.0  1.0  1.0
22     0.0  0.0  0.0

In [106]:
#Looking to see the realtion between kills and losing team kills, compared to gold
df.groupby(['kills'])[('losingteamKills','goldDiff')].describe(percentiles=[])

<ipython-input-106-bb244656f005>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['kills'])[('losingteamKills','goldDiff')].describe(percentiles=[])

      losingteamKills                                     goldDiff  \
                count      mean       std  min  50%   max    count
kills
0                10.0  3.600000  1.646545  1.0  4.0   6.0     10.0
1                42.0  4.095238  2.397250  0.0  4.0   9.0     42.0
2               146.0  4.417808  2.321583  1.0  4.0  11.0    146.0
3               303.0  4.610561  2.652030  0.0  4.0  15.0    303.0
4               430.0  4.841860  2.534262  0.0  5.0  15.0    430.0
5               612.0  4.831699  2.577018  0.0  5.0  16.0    612.0
6               635.0  5.256693  2.682799  0.0  5.0  15.0    635.0
7               668.0  5.196108  2.502565  0.0  5.0  15.0    668.0
8               609.0  5.510673  2.584169  0.0  5.0  14.0    609.0
9               499.0  5.162325  2.562414  0.0  5.0  13.0    499.0
10              341.0  5.636364  2.654025  0.0  6.0  14.0    341.0
11              267.0  5.411985  2.747987  0.0  5.0  14.0    267.0
12              177.0  5.564972  2.700487  0.0  5.0  15.0    177.0
13               94.0  5.585106  2.398071  1.0  5.0  12.0     94.0
14               59.0  5.627119  2.827807  1.0  6.0  12.0     59.0
15               30.0  5.933333  2.572177  0.0  6.0  10.0     30.0
16               19.0  6.421053  3.060788  1.0  6.0  11.0     19.0
17                3.0  6.000000  2.645751  4.0  5.0   9.0      3.0
18                2.0  9.000000  0.000000  9.0  9.0   9.0      2.0
19                2.0  3.500000  2.121320  2.0  3.5   5.0      2.0
22                1.0  5.000000       NaN  5.0  5.0   5.0      1.0


              mean          std     min     50%      max
kills
0     -1759.500000  1223.749089 -3460.0 -1897.0    174.0
1     -1562.309524  1567.549517 -4939.0 -1336.0    953.0
2      -945.684932  1404.641772 -4607.0 -1013.5   2825.0
3      -555.729373  1552.593184 -6744.0  -428.0   2507.0
4      -212.744186  1533.856328 -5255.0  -142.5   4279.0
5       322.171569  1605.836527 -5113.0   396.5   4179.0
6       678.177953  1619.806669 -4375.0   814.0   6309.0
7      1129.943114  1624.097710 -4646.0  1157.5   6869.0
8      1556.082102  1679.499393 -3224.0  1535.0   9341.0
9      2249.709419  1682.367912 -3315.0  2169.0   7285.0
10     2461.246334  1718.430951 -2100.0  2602.0   7839.0
11     2912.883895  1839.361242 -2782.0  2930.0   7952.0
12     3520.192090  1763.025540 -1843.0  3587.0  10830.0
13     3946.287234  1709.242652   -42.0  3974.5   8472.0
14     4459.966102  1648.572109  1004.0  4473.0   7655.0
15     4422.333333  1797.064183  1961.0  4394.0   9152.0
16     5014.578947  1502.275027  2529.0  5377.0   7868.0
17     5147.333333  1195.402164  3887.0  5290.0   6265.0
18     3734.000000   328.097546  3502.0  3734.0   3966.0
19     9097.500000  1741.604002  7866.0  9097.5  10329.0
22     7278.000000          NaN  7278.0  7278.0   7278.0

In [9]:
#reframing so that gold diff as the main category, seems like it is a pretty good tell of who will win
dfGold = df.groupby(['goldDiff'])[('kills','losingteamKills')].describe(percentiles=[])

<ipython-input-9-9b9de3a732a3>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  dfGold = df.groupby(['goldDiff'])[('kills','losingteamKills')].describe(percentiles=[])

In [ ]:
#ploting dfGold  to see correlation between goldDiff amount and winning
df

In [7]:
#looking to see if I put the graph interms of losing team point of view if it will change anything
df.groupby(['losingteamKills'])[('kills','goldDiff')].describe(percentiles=[])

<ipython-input-7-ccdc309243bb>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['losingteamKills'])[('kills','goldDiff')].describe(percentiles=[])

                 kills                                     goldDiff  \
                 count      mean       std  min  50%   max    count
losingteamKills
0                 54.0  6.351852  2.734527  1.0  6.0  15.0     54.0
1                253.0  6.395257  2.965726  0.0  6.0  16.0    253.0
2                460.0  6.778261  2.966546  0.0  7.0  19.0    460.0
3                662.0  6.652568  2.844452  0.0  7.0  16.0    662.0
4                703.0  7.069701  2.922451  0.0  7.0  17.0    703.0
5                752.0  7.199468  2.981541  1.0  7.0  22.0    752.0
6                647.0  7.357032  2.856887  0.0  7.0  16.0    647.0
7                505.0  7.360396  2.862735  1.0  7.0  16.0    505.0
8                377.0  7.360743  2.778594  1.0  7.0  15.0    377.0
9                224.0  7.593750  3.017164  1.0  7.0  18.0    224.0
10               154.0  7.902597  3.105486  3.0  7.0  16.0    154.0
11                86.0  8.034884  3.031007  2.0  8.0  16.0     86.0
12                40.0  8.575000  2.790896  3.0  9.0  14.0     40.0
13                15.0  7.133333  2.263583  3.0  7.0  12.0     15.0
14                10.0  7.100000  2.846050  3.0  6.5  11.0     10.0
15                 6.0  6.333333  3.141125  3.0  6.0  12.0      6.0
16                 1.0  5.000000       NaN  5.0  5.0   5.0      1.0


                        mean          std     min     50%      max
losingteamKills
0                3636.777778  1655.501904   388.0  3549.5   8461.0
1                3167.786561  1926.059460  -599.0  2955.0  10830.0
2                2725.780435  1870.916274 -1684.0  2508.5  10329.0
3                2102.392749  1677.420663 -1916.0  1972.0   7666.0
4                1802.945946  1765.079835 -3133.0  1806.0   7480.0
5                1258.648936  1735.285926 -2975.0  1100.0   7866.0
6                 916.438949  1717.508943 -3460.0   843.0   6105.0
7                 401.459406  1667.342165 -4939.0   325.0   5941.0
8                -103.432361  1721.857941 -4674.0  -166.0   5540.0
9                -517.830357  1738.967695 -4869.0  -568.5   4473.0
10               -887.564935  1895.390580 -5113.0  -999.0   4236.0
11              -1078.209302  1752.725045 -4581.0 -1211.5   4259.0
12              -1313.775000  1654.738937 -5767.0 -1161.5   2340.0
13              -2343.600000  1397.935611 -4947.0 -1852.0   -468.0
14              -3379.100000  1672.664305 -6744.0 -3506.5   -814.0
15              -3681.666667  1960.204445 -5255.0 -4510.5    -84.0
16              -2899.000000          NaN -2899.0 -2899.0  -2899.0

In [4]:
#looking see if wards placed relates to golddiff, probably need to take out all the one off's 
dfWards=df.groupby(['wardsPlaced'])[('losingTeamWardsPlaced','goldDiff')].describe(percentiles=[])

<ipython-input-4-7d2309088fad>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  dfWards=df.groupby(['wardsPlaced'])[('losingTeamWardsPlaced','goldDiff')].describe(percentiles=[])

In [8]:
df.groupby('kills').agg({'goldDiff': ['mean']},{'losingTeamWardsPlaced':['mean']})

          goldDiff
              mean
kills
0     -1759.500000
1     -1562.309524
2      -945.684932
3      -555.729373
4      -212.744186
5       322.171569
6       678.177953
7      1129.943114
8      1556.082102
9      2249.709419
10     2461.246334
11     2912.883895
12     3520.192090
13     3946.287234
14     4459.966102
15     4422.333333
16     5014.578947
17     5147.333333
18     3734.000000
19     9097.500000
22     7278.000000